### ISSUE TITLE
NOV2021: Color codes not working in WiFi selection on startup

### ISSUE THREAD

**Issue by atanisoft** [stuartpittaway/diyBMSv4ESP32#105]
On startup of the NOV2021 code on an ESP32 without persisted WiFi configuration the WiFi selection output is using color codes which are not interpreted in all environments:
```
DIYBMS CONTROLLER - Scanning Wifi

Number	SSID Name                             RSSI	Channel
␛[36m0:	␛[33mTheHomeNet_2GEXT␛[39m                      -42	6
␛[36m1:	␛[33mNETGEAR53␛[39m                             -55	1
␛[36m2:	␛[33mTheHomeNet␛[39m                            -57	6
␛[36m3:	␛[33mjaynical␛[39m                              -60	11
...
```
This appears to be the only place within the BMS that is using color codes. Colors should likely be optionally enabled via `CONFIG_LOG_COLORS` (which controls `ESP_LOGX` color usage).

**Comment by stuartpittaway** [comment]
Fixed.
