### ISSUE TITLE
Flashing cell modules

### ISSUE THREAD

**Issue by omixxer** [stuartpittaway/diyBMSv4ESP32#118]
Hi Stuart,
I'm having trouble flashing cell modules. When I try to load the V440 from the code, I get a message with an error that says this:
avrdude: Device Signature = 0x1e9215 (probably t441)
avrdude: expected signature for ATtiny841 is 1E 93 15

How can it be fixed?

**Comment by stuartpittaway** [comment]
It looks like you have the wrong ATTINY chip - its found an ATTINY`4`41 and you should be using an ATTINY`8`41
