### ISSUE TITLE
relay pulse goes on for ever when activated?

### ISSUE THREAD

**Issue by virtuvas** [stuartpittaway/diyBMSv4ESP32#123]
ignore my code snipset, 

code is fine as is, however, on the one system it pulses indefinitely, on the test system at home it works fine. I'll come back once I get more info from onboard.

cheers

V.

**Comment by stuartpittaway** [comment]
Ok. The actual relay state in the variable should be on. However the relay should only pulse.

**Comment by virtuvas** [comment]
discard, me being silly, had only edited the trigger value to de-activate the relay and check that cabling works, and had forgotten to also edit the second restore value...
Checked again today, all is working fine!

V.
