### ISSUE TITLE
The last firmware does not create the ap mode

### ISSUE THREAD

**Issue by pablo170** [stuartpittaway/diyBMSv4ESP32#128]
I installed the Last firmware, but I had to do downgrade because on the screen was shown configure wifi settings with the White led, but the ssid diybms controller wasn't discoverable.

**Comment by atanisoft** [comment]
AP mode is not supported in the latest firmware, you can configure your WiFi via the USB interface.

**Comment by pablo170** [comment]
Thank you so much for your fast response.

**Comment by s1738berger** [comment]
Maybe you could remove this section about the AP on this page ( Method 1 - WiFi Access Point ):
https://github.com/stuartpittaway/diyBMSv4ESP32/blob/master/ProgrammingHardware.md
