### ISSUE TITLE
No German translation

### ISSUE THREAD

**Issue by s1738berger** [stuartpittaway/diyBMSv4ESP32#143]
If I choose German it shows up as **Language: de** on the page **About**, but no texts are shown in German.
Other languages seem to work as expected. I use the prebuilt version from 2022-08-16, `53fc96cd8b1e992f76d34a80da93ae04e0edccb0`.
Was the same bhaviour in earlier versions as well.

**Comment by moscito1010** [comment]
Stuart, how can we help you? That shouldn't be a problem for us to translate all the texts into German for you. Is there a language file that we can edit?

**Comment by stuartpittaway** [comment]
This is the file where the translation texts reside..

https://github.com/stuartpittaway/diyBMSv4ESP32/blob/master/ESPController/web_src/lang_de.js

It would be a case of editing that file, which can then be "pushed" into GITHUB for review/approval.

**Comment by stuartpittaway** [comment]
The translation should now work, if you upgrade the firmware!

**Comment by s1738berger** [comment]
It works now. The grman translation seems to be complete.
Thank you very much for the quick fix.
regards Stefan
