### ISSUE TITLE
Relay not working correctly

### ISSUE THREAD

**Issue by jan-kratochvil** [stuartpittaway/diyBMSv4ESP32#153]
I have a strange issue, and don't know if its due to my setup, or it's common problem.
My setup is:
Relay default: ON
Pack under voltage (mV) Trigger value: 49000, Reset value: 52000, state: OFF
It should disconnect load if under 49V and reconncet if above 52V.

It worked for a week, but suddenly it did not switch the Relay ON, when voltage rose above 52V. I monitor the Relay state with MQTT and it reports the ON state, and on the Rules page the Rule is not green. I thought the hardware failed, but when I reset the Controller from the GUI, the Relay switches ON and works as expected.

Is there somethig, I could monitor, where the problem could be?

**Comment by stuartpittaway** [comment]
Hello,

You mention that the rule was not "green" when the voltage was above 52V - this is to be expected as the rule would be "off" at that point (its not under voltage), so the default relay state should be active then - "ON" in this case.

You might find that keeping the relay on for very long periods of time isn't good for power consumption or the life of the relay.  Perhaps swap to using the normally open or closed contacts instead, and flip the operation of the rules?

**Comment by jan-kratochvil** [comment]
Yes, the rules in the GUI and MQTT backend work, the problem is the physical Relay (and the LED on board), that is not following this behavior.

I could try to swap the NO/NC contacts and logic, but my idea was to use fail safe system with NO.

I will look into the code, how the Relay switch works.

My question here is mostly about if someone else is not experiencing similar problems.

**Comment by stuartpittaway** [comment]
Ok, if the relay has been powered on for several weeks I suspect it may have failed - perhaps check the relay with a multimeter to see if the coil has shorted?

**Comment by jan-kratochvil** [comment]
It's not problem of the HW, because if I make soft-reset of the controller, everything works fine. I will have to figure out how often this problem occurs.

**Comment by stuartpittaway** [comment]
Ok - thats very strange.

**Comment by stuartpittaway** [comment]
Can you upload a photo of the ESP32?  The RED LED shouldn't normally be blinking.

**Comment by jan-kratochvil** [comment]
https://user-images.githubusercontent.com/10809796/211546686-6da096d0-8f33-4889-9e88-cb294c40bb9e.mp4

This it the locked/broken state

**Comment by jan-kratochvil** [comment]
https://user-images.githubusercontent.com/10809796/211546867-9cd2bb90-ceac-4712-b9f8-6679119e108e.mp4

this is the normal/working state, the led is blinking/flashing

**Comment by stuartpittaway** [comment]
How are you powering the board?

The led shouldn't be flashing, is that the power led?

**Comment by jan-kratochvil** [comment]
Hi I'm powering the BMS with 5V/2A adapter, I think this led is the D2 pin led, I have this version of the board, may by this it the problem.

![obrazek](https://user-images.githubusercontent.com/10809796/211641000-9475bbcf-8229-4b5b-841b-ca53f5e55c89.png)

**Comment by jan-kratochvil** [comment]
OK, I will switch the power supply and report back.

**Comment by stuartpittaway** [comment]
Did you get any success with a different power supply?

**Comment by jan-kratochvil** [comment]
Hi, I didn't get to it yet, hope I will soon....
