### ISSUE TITLE
No temperature displayed

### ISSUE THREAD

**Issue by Chris87-ux** [stuartpittaway/diyBMSv4ESP32#155]
Hi @stuartpittaway,
I just flashed the latest Software (09. of Dec 2022) on a controller and also flashed the modules with the 5k version of the software.
after connecting everything, no temperature had been displayed. 
The rule (module Temp over 60°C) is active.

![image](https://user-images.githubusercontent.com/55442459/208772348-ea539ca4-a2e0-4aea-b7e8-4f9e9ca04b58.png)
![image](https://user-images.githubusercontent.com/55442459/208772618-f6e7de3d-7aad-4321-87ca-804975785c38.png)

In case, future informations are needed, just ask.
/ Chris

**Comment by stuartpittaway** [comment]
Ok, somethings not correct there - the module temps are also -40 ?

Did you solder the ATTINY chip yourself?  This sounds like a problem with pin 9.

Also check the JST power cables you have - I can see bare wire/metal in the photo - you don't want that to short out!

**Comment by Chris87-ux** [comment]
Hello, thanks for the fast reply. 
I have the same controller and module board ( same Order) running already since over 1 year, without problems and updates. so i dont suspect any hardware issue.
Yes, i soldered the ATTiny myself.
Here some additional pictures, as it has been quiet late yesterday:
![image](https://user-images.githubusercontent.com/55442459/208860966-587bdc13-0dbe-4e2d-8e87-67e7174377d4.png)
![image](https://user-images.githubusercontent.com/55442459/208861034-8d1ae116-314e-4a18-92c9-5c5f49e8edab.png)


Thanks regarding the hint with the bare wire, I'm on it, but it is quiet difficult to crimp 0,75mm² wires to this JST.
New boards to come ;-)
![image](https://user-images.githubusercontent.com/55442459/208860823-ec2138b0-49d3-429e-95c3-2609e5e293c0.png)

**Comment by stuartpittaway** [comment]
Did you have any problems with R19?  That part should be CMFB103F3950FANT - did you substitute it when ordering from JLCPCB?

If you put a multimeter across it (resistance) the value should change when you put your finger on the part (heat/cold).

**Comment by Chris87-ux** [comment]
At roomtemperature it has 7,71kOhm, after heating up a bit it has 7,42kOhm.
I din't changed anything at the R19, as mantioned olderones from the same Order works great.

For the programming I used the AVR programming mode from the Controller.

**Comment by stuartpittaway** [comment]
Ok.

Can you check that when you broke off the temp sensor PCB board, that the two connections (small holes/vias) on the edge of that "snap" point are not shorted together?

Pins 5, 9 and 13 on the ATTINY chip control the temperature sensor reading - check the soldering around those parts.

**Comment by Chris87-ux** [comment]
Ok, 
what i did now:
I had an other controller here, with the Software from 26.Feb. 2022.
I flashed one other board  with the 5k .hex over this controller.
Thank I changed to only one module on this "older" controller and i can see temperaturs again.

**Comment by stuartpittaway** [comment]
If you click on the "modules" page and "configure" against a working module, can you give me the version number please?

![image](https://user-images.githubusercontent.com/1201909/208872880-a404993e-d20b-4273-bf07-3879f4cb78f7.png)

**Comment by Chris87-ux** [comment]
Now I reflashed one of the "boards were no temperature is shown" with the 5k.hex from the "older controller" and both temperatures are shown.

Than I connected the new controller again and al temperatures are shown.

**Comment by stuartpittaway** [comment]
Right - can you provide the module version from one of the modules that DOESNT work ?

**Comment by Chris87-ux** [comment]
now its getting interesting...
![image](https://user-images.githubusercontent.com/55442459/208874131-5d20fcba-bd8a-48c3-9da9-3713d64d4568.png)
 both modules have the same verison.
ID 0= programmed with new controller software
ID 1= programmed with older controller software

**Comment by stuartpittaway** [comment]
Ok, now that's weird!

I can't see source code version d2984b7b in GITHUB - was this one of the pre-compiled releases or did you compile yourself?

**Comment by Chris87-ux** [comment]
It was the precomiled one.
![image](https://user-images.githubusercontent.com/55442459/208877203-7dfc22d3-a35a-4868-8c62-c9c03190cc16.png)

**Comment by stuartpittaway** [comment]
Ok, did you actually use that version 2022-12-09-15-10 ?

If so, the modules should have a version number of "3bc74c95"

**Comment by Chris87-ux** [comment]
after a restart of the controller it showed this:
![image](https://user-images.githubusercontent.com/55442459/208880523-0c047429-ff77-4a14-ba9f-eaf9b3754edd.png)
could this be some kind of caching issue?

**Comment by stuartpittaway** [comment]
Yes, that data does get cached.

Let me go away and test a few scenarios out.

**Comment by Chris87-ux** [comment]
Thanks very much!!! 
Short-cut would be now, programm modules with the Software from Feb. 2022 and connect controller Dec. 2022 ;-)

**Comment by stuartpittaway** [comment]
Good news is that I've repeated the issue you see - bad news I've now got to fix it!

**Comment by Chris87-ux** [comment]
;-) Good news, I'm not just stupid.

Thanks again for your great work!!!

**Comment by Chris87-ux** [comment]
![image](https://user-images.githubusercontent.com/55442459/208910963-762dc37b-9f68-4f4a-9486-edcaed76d7bb.png)
ID 0 is the new flashed board, everything great and working.

Somehow i had an huge issue getting the Board connected to wifi, but that was probably nothing important, as it works finally.

Fixed!!  Thanks very much for your Work.

**Comment by stuartpittaway** [comment]
Great!
