### ISSUE TITLE
Compilation fails during first week of the year

### ISSUE THREAD

**Issue by chron0** [stuartpittaway/diyBMSv4ESP32#158]
**Describe the bug**

Compilation fails during first week of the year with:

```
include/EmbeddedFiles_Defines.h:22:49: error: expected primary-expression before ';' token
 static const uint8_t COMPILE_WEEK_NUMBER_BYTE = ;
```

which is probably due to buildscript_versioning.py line 91:

```
f.write(datetime.datetime.utcnow().strftime("%W").lstrip("0"))
```

when I run this in python console I get this result as well:

```
>>> import datetime
>>> datetime.datetime.utcnow().strftime("%W").lstrip("0")
''
>>> datetime.datetime.utcnow().strftime("%W")
'00'
```

**Comment by chron0** [comment]
```
datetime.datetime.utcnow().isocalendar()[1]
```

could be an alternative here.

**Comment by chron0** [comment]
```
f.write(str(datetime.datetime.utcnow().isocalendar()[1]))
```

works for me now.

**Comment by stuartpittaway** [comment]
I fixed this earlier today, it's in the pylontech branch.

**Comment by chron0** [comment]
ah perfect, I'll close this then :)

**Comment by N1c084** [comment]
Thanks for this .
When I compile a contrôler file and upload it by node mcu (1450ko) bin files it won't boot .
But when I compile and upload directly by platform io it work .🤔

Any idea ?

**Comment by stuartpittaway** [comment]
The nodemcu files are complete flash images, not just the code. 

Platform IO only uploads the code, so the upload is smaller.

I use GitHub action to build the nodemcu files in the correct format.
