### ISSUE TITLE
Some Current & Voltage Monitoring settings disappear after Controller reboot

### ISSUE THREAD

**Issue by deekoowee** [stuartpittaway/diyBMSv4ESP32#159]
Hi,

**Hardware/Software Versions**
Controller version v4.2
Processor: ESP32
Version: LocalCompile
Compiled: 1.1.2023

**To Reproduce**
1. PZEM-017 connected to Controller.
2. Saved the basic settings. All settings available until I make controller reboot.
3. Marked settings disappears after reboot.
4. ![Capture](https://user-images.githubusercontent.com/121685906/210199356-46cbed5f-2536-4efd-9b60-da4334b9fb04.JPG)

**Comment by stuartpittaway** [comment]
Hello, as mentioned on the screen "PZEM-017 uses 75mV shunts, state of charge and alarms are not supported on this device."

The values you have highlighted are all related to the state of charge - which the PZEM-017 doesn't support.
