### ISSUE TITLE
If you change the language, the rules are displayed incorrectly

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4ESP32#164]
If you change the language, the rules are displayed incorrectly and the information "minutes since midnight" is missing.

**Comment by stuartpittaway** [comment]
Which language, and which version of the code?

**Comment by moscito1010** [comment]
oh sorry. the newest compiled firmware (master) and all languages without english.
in the pylontech brunch is it the same.

**Comment by moscito1010** [comment]
Here a pic with pylontech branch
![lang_bug](https://user-images.githubusercontent.com/75945899/216768550-30bff637-4132-4a62-9359-d9d65a6fca33.JPG)

**Comment by stuartpittaway** [comment]
Thank you for raising this problem.  I believe this is now fixed, in the pylon branch.

![image](https://user-images.githubusercontent.com/1201909/216968780-5dc0d99e-f44e-4dce-8bec-896cac6352ff.png)
