### ISSUE TITLE
No Voltage1 and Range1 on Home Site with two Banks

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4ESP32#166]
if i go to the HOME Site i can´t see the voltage and range from Bank1. I see only Bank0
in the Tiles site i see 2 banks

i use
latest release 2023-02-14

**Comment by stuartpittaway** [comment]
Can you upload a screenshot?

**Comment by moscito1010** [comment]
yes
![image](https://user-images.githubusercontent.com/75945899/218832477-a89b0fd5-4eae-426f-9c25-940d63b1644b.png)
![image](https://user-images.githubusercontent.com/75945899/218832528-3ce7d060-071f-47a8-b38d-4a070899769c.png)

**Comment by stuartpittaway** [comment]
Ok, this is by design. When on the tiles page, click on the tile you want to be visible on the home page.

You can toggle them on/off

**Comment by moscito1010** [comment]
oh, Stuart, I'm just embarrassed. I didn't know this function existed. Please excuse me.

**Comment by stuartpittaway** [comment]
The feature was only added in this latest release.
