### ISSUE TITLE
Missing "Minutes after midnight" with display settings in German

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4ESP32#167]
i can´t see the minutes after midnight if i change the language to german

use latest release 2032-2-14

**Comment by stuartpittaway** [comment]
Can you upload a screenshot please

**Comment by moscito1010** [comment]
no problem
![image](https://user-images.githubusercontent.com/75945899/218831914-647fb4c4-a5a0-436d-939a-297eea2d2585.png)
![image](https://user-images.githubusercontent.com/75945899/218832285-09b2e85c-8283-44d3-8163-21c5598ead03.png)

**Comment by Bingo2023** [comment]
I just saw this...
check issue 168
https://github.com/stuartpittaway/diyBMSv4ESP32/issues/168

It is same route cause. Translated german rows are wrong.

**Comment by stuartpittaway** [comment]
> Translated german rows are wrong.

The translation should be resolved/fixed now (see the screenshot in this issue) - the missing "minutes" value is still a problem though.
