### ISSUE TITLE
Rule-translation error

### ISSUE THREAD

**Issue by Bingo2023** [stuartpittaway/diyBMSv4ESP32#168]
**Describe the bug**
error in german translation.
See screenshots of rule page for details.

**Hardware/Software Versions**
Controller version (from PCB): 4.5
(below can be obtained from the "About" page in the controller web interface)
Processor: ESP32
Version: v4.4.1-1-gb8050b365e
Compiled: Compiled_Firmware_2023-01-03-10-09

**To Reproduce**
1. switch to german -> reboot
2. configure rules (in german language) -> reboot to make sure rules are saved
3. switch to english language -> reboot
4. compare rule settings

![2023-02-14_20h49_45](https://user-images.githubusercontent.com/61052575/218850345-374bc5a3-fabe-424f-b461-1487493b846e.png)

![2023-02-14_20h51_52](https://user-images.githubusercontent.com/61052575/218850389-dd7884ad-d046-40f1-aba8-1a7a3afbeac6.png)

the two screenshots show the values of rules are not changed, just the translation is switched.
In my case the BMS is connected to a real 16S Battery. As you can see the rule "Pack over voltage" is triggered because translated rows are mixed up. Note duplicate rows of Timer 1 and Timer 2

Fixing this should be easy via adaption translation files.

**BUT can we do something to prevent this in future? In my opinion it is a security risk as this can prevent the BMS from protecting against Over/unter voltage [MAIN reason for a BMS].**

**Comment by stuartpittaway** [comment]
Can you update to the latest release please (from today)?

**Comment by smurfix** [comment]
Don't forget the nonsense at the top.

**Comment by smurfix** [comment]
Should be "Not-Aus", "interner Fehler im BMS", "maximaler Strom (A)".

**Comment by stuartpittaway** [comment]
Ok, label text amended

![image](https://user-images.githubusercontent.com/1201909/219065172-5fbc76b8-7b9e-42a8-b0f2-5b1bd4bdbb76.png)

**Comment by stuartpittaway** [comment]
@Bingo2023 can you confirm this is now fixed?
