### ISSUE TITLE
Victron VE.CAN - CVL handling

### ISSUE THREAD

**Issue by Bingo2023** [stuartpittaway/diyBMSv4ESP32#175]
SW-Version: [Release-2023-02-20-09-53](https://github.com/stuartpittaway/diyBMSv4ESP32/releases/tag/Tag-2023-02-20-09-53)

In general, on Victron (VE.CAN), setting "CVL" (Charge Voltage Limit) = 0 V means we have Batterie-Overvoltage -> discharge battery with full power.

- So I we set option "Prevent charging" -> CVL goes to 0V and battery gets discharged rapidly. I tried to avoid damage by setting CCL = 10A but also this gets ignored (in my case discharging w/ 100A.... :( )

- I guess same for Option "Prevent discharging" but I did not feel like trying this.... 

![2023-02-20_20h29_52](https://user-images.githubusercontent.com/61052575/220186359-8796ef97-366c-414d-8db1-e7841d990fe0.png)
![2023-02-20_20h29_15](https://user-images.githubusercontent.com/61052575/220186375-21fcf6f6-c5fd-4fd7-b1bf-ca3f0cbdb3d1.png)

**Comment by Bingo2023** [comment]
Another thing regarding CVL handling:

I experienced this today afternoon while charging battery.
CVL gets calculated by some function (voltage-level changes during charging).
So it was not possible the charge battery to full SOC, I stuck at ~50% because charge-voltage is limited -> power will get reduced.

In my understanding (I work in automotive e-mobility area), we should simply send the voltage defined on this page via CAN (in the pictures 58,0 V).
All limitations is only done via current limitation.

To me it is not clear how the setting block "Discharging" is supposed to work.
I think we need something like this (green color). Limiting current toward lower end until 0A (usually linear dearating is enough).



![2023-02-20_20h49_35](https://user-images.githubusercontent.com/61052575/220188493-e024f59c-2909-4b13-be33-ff3037e4ded8.png)
![2023-02-20_20h49_02](https://user-images.githubusercontent.com/61052575/220189909-c7d89d9c-16b8-4f59-88b7-6a3255aa774a.png)

**Comment by stuartpittaway** [comment]
Have you updated to today's release? #173 is related to this

**Comment by stuartpittaway** [comment]
Ok, I was unaware of the cvl zero issue, is this documented somewhere?

Victron recommend using voltage as the main limiting factor when charging battery, not current.

**Comment by stuartpittaway** [comment]
The value of 3500mV for the linear curve is also too high, it should be around 3200

**Comment by Bingo2023** [comment]
> Ok, I was unaware of the cvl zero issue, is this documented somewhere?
> 
> Victron recommend using voltage as the main limiting factor when charging battery, not current.

The control loop always has an voltage limit as setpoint that is correct, but there is also a second control loop that limits the current (value should come from limiting device can be charger or battery or whatever).
During charging the control loop is always limited in current until the very last few percent before 100% SOC.

**Comment by Bingo2023** [comment]
> The value of 3500mV for the linear curve is also too high, it should be around 3200
Thx, I will try with 3200mV. I've also watched the new video and found the code provided by Matthias.
I will test voltage limitation more deeply in the next days. On my setup it VCL is less that 1V over battery voltage, sometimes even same level... this will almost prevent charging...

**Comment by stuartpittaway** [comment]
> On my setup it VCL is less that 1V over battery voltage, sometimes even same level... this will almost prevent charging...

Ok, try lowering the "sensitivity" value then - however as long as there is a voltage difference, charging shouldn't be affected.

I'll modify the code to avoid using "zero volt" when charging is disabled/not wanted.

**Comment by stuartpittaway** [comment]
@Bingo2023 I've updated the code with fixes for sending a zero voltage to Victron.

I've just noticed that the screenshot you uploaded had sensitivity set to "50" - that should be like "1.5" - probably the reason why you see such low charging voltages.

**Comment by stuartpittaway** [comment]
> To me it is not clear how the setting block "Discharging" is supposed to work.

Presently, there is no dynamic control on the discharge parameters - discharge is simply prevented when the cell and/or bank voltage goes below the setting.

**Comment by Bingo2023** [comment]
Hello Stuart,
thx for the extremely fast reaction :)
The release
[Release-2023-02-21-08-55](https://github.com/stuartpittaway/diyBMSv4ESP32/releases/tag/Tag-2023-02-21-08-55)
is working with Victron.
Also it seems that the proposed setting helps the chargevoltage. I'll test these days more and give feedback.
