### ISSUE TITLE
Manually setting SoC does not work

### ISSUE THREAD

**Issue by laserranger3000** [stuartpittaway/diyBMSv4ESP32#177]
I tried setting the SoC manually to 100% (from 105%), but it didn't do anything.
Now it seems to be permanently stuck at 105%.
I tried it another time with 99%, but same behavior.

**Comment by stuartpittaway** [comment]
Have you updated the firmware on the current shunt recently?  This only works on newer code versions - this is the latest release https://github.com/stuartpittaway/diyBMS-CurrentShunt/releases/tag/Tag-2023-01-25-12-26

**Comment by laserranger3000** [comment]
I wasn't aware of the new shunt firmware, I guess that explains my issue :)

Did I break something with my mismatching firmware combination? As I said, the SoC does not seem to update anymore and is stuck at 105%

**Comment by stuartpittaway** [comment]
I've completely re-wrote the SoC calculation in the new firmware - so give it a go.

**Comment by stuartpittaway** [comment]
Hi @laserranger3000 did you get this working?
