### ISSUE TITLE
Victron Cerbo GX V2.93 - no Battery load in ESS with Quattro II and MPPT

### ISSUE THREAD

**Issue by HerrFrodo1** [stuartpittaway/diyBMSv4ESP32#179]
Problem: the PV does not charge the battery, although VCL, CCL and DCL are correctly transmitted to the Cerbo via CAN bus.  All settings in DVCC and ESS have been checked.  Several reboots and firmware downgrades have been tested.  Apparently the Cerbo did an automatic update and suddenly the ESS stopped working properly.  I then downloaded a firmware beta version for the Cerbo (V3.0-18) and after that everything worked again!

**Hardware/Software Versions**
Controller version (from PCB): 4.5

Processor: ESP32
Version: 7780f30b8fd333e90c7ba5f930b68b447d958c9f
Compiled: 2023-02-21T08:54:23.262Z

**Comment by HerrFrodo1** [comment]
I don't tested it with Cerbo firmware v2.92. 

maybe it could work again with the downgraded one.

**Comment by red0909** [comment]
i have 2.92 on raspberry, DVCC is working good.

**Comment by stuartpittaway** [comment]
@HerrFrodo1 is this now working for you since you changed the firmware on the Cerbo (to V3.0-18) ?

**Comment by HerrFrodo1** [comment]
> @HerrFrodo1 is this now working for you since you changed the firmware on the Cerbo (to V3.0-18) ?

@stuartpittaway Yes! Only the new Beta works. 

I deactivated automatic updates in my Cerbo GX.

**Comment by Bingo2023** [comment]
I'm running Venus OS V3.0-15 on Raspberry Pi3 - also working.

Generall Victron gernerates lots of beta version, and they are partly buggy, see V3.0-17 with huge Node-Red issue...
