### ISSUE TITLE
Possibility to set Static IP

### ISSUE THREAD

**Issue by Chris87-ux** [stuartpittaway/diyBMSv4ESP32#183]
Hello, I use a bigger network with all important devices set as Static within this network, it would be great to have this option also with this DiyBMS.

**Comment by atanisoft** [comment]
Static IP on the device is a bit more challenging than having your DHCP server provide a fixed IP for a given MAC address. In a larger network this is the typical approach used (MAC address binding to IP), so I'd suggest using that instead.

**Comment by stuartpittaway** [comment]
A DHCP reservation sounds like a quicker solution - is this something your environment supports @Chris87-ux ?

**Comment by Chris87-ux** [comment]
thanks @atanisoft and @stuartpittaway, sure both would work and it is OK, i can go with it. It would be just great, if Static IPs could be used in a easy way. If this is to much work, please disregard this enhancement. 
Thanks for all your great work ;-)

**Comment by Jestergnet** [comment]
Also for the implementation of this idea.
