### ISSUE TITLE
External Current Shunt - Basic Settings multiplied by 10

### ISSUE THREAD

**Issue by deekoowee** [stuartpittaway/diyBMSv4ESP32#185]
**Describe the bug**
When saving the basic settings, settings will be changed. Tried with several computers and browsers. Always the same result.
I'm not sure, but few weeks ago settings have saved correctly (battery was not fully charged). Now the battery is fully charged to top limit 58.8V and saving problem started.

**Hardware/Software Versions**
Controller version (from PCB): 4.2
Processor: ESP32
Version: a21d13edc38a212d7bd5366c9cbb3858a885eaa1 
Compiled: 2023-03-01T09:16:31.399Z

**To Reproduce**
1. Set the values
![Capture](https://user-images.githubusercontent.com/121685906/225344108-cea1885c-f906-4ff5-866e-c6894b4c5c99.PNG)
2. Click on 'Save basic settings'
3. Result
![Capture1](https://user-images.githubusercontent.com/121685906/225344251-6001eff3-2619-40a6-bcdf-d49542ec6faf.PNG)

**Comment by deekoowee** [comment]
Tested with earlier version 14th Feb 2023 and worked ok.
It doesn't change the values.

**Comment by stuartpittaway** [comment]
Thanks for reporting this bug, think I know what it is.

**Comment by stuartpittaway** [comment]
Hi @deekoowee 
I've just merged into the master branch some changes to fix this issue.  Would you be able to confirm it now works using that version?

https://github.com/stuartpittaway/diyBMSv4ESP32/releases/tag/Tag-2023-03-16-15-47

**Comment by deekoowee** [comment]
Hi @stuartpittaway 
I programed the new version into controller.
Now the saving works ok and do not change the values.
Thanks for this fix.

**Comment by stuartpittaway** [comment]
Perfect, thanks for the feedback
