### ISSUE TITLE
Charge/Discharge configuration problem

### ISSUE THREAD

**Issue by deekoowee** [stuartpittaway/diyBMSv4ESP32#190]
Hi,
Tried few settings for inverter and found some trouble with them.
Goal was to prevent charging/discharging and how is it managed by inverter.
Prevent discharging did not actually stop battery discharging.
Amp-hours reset from 830 back to 280 
Unchecking the Prevent charging and Prevent discharging do not work. Settings remain saved somewhere.

**Hardware/Software Versions**
Controller version (from PCB): 4.2
Processor: ESP32
Version:  e861a254201a9526f29e00371e471e47b71b5a06 
Compiled: 2023-03-16T15:45:16.346Z

**To Reproduce**
1. Set 'Amp-hours' to 830
2. Check 'Prevent charging' and 'Prevent discharging'
3. Save settings
4. Unheck 'Prevent charging' and 'Prevent discharging'
5. Save settings
6. Refresh browser (F5)
![Capture](https://user-images.githubusercontent.com/121685906/227224391-a5ce45f7-763a-40d0-b74c-82b8d38f1a1f.PNG)

**Comment by HerrFrodo1** [comment]
Hi!

Please download and install the latest Release. 
Stuart solved this problems a few weeks before. 
Greetings

**Comment by stuartpittaway** [comment]
@deekoowee what hardware (inverter/charger) are you using?

**Comment by deekoowee** [comment]
@HerrFrodo1 
Thanks for the release info, I didn't noced that.
I made firmware update, but same notes at left upper corner, when refreshing browser page.

**Comment by deekoowee** [comment]
@stuartpittaway 
I have Imeon 9.12
Charging worked until I check those boxes.

**Comment by stuartpittaway** [comment]
Its possible that you simply refreshed the browser page before the controller updated its internal settings. There is a delay of 3 or 4 seconds.

However, does the charging now work for you using the PylonTech emulation?

**Comment by deekoowee** [comment]
I refreshed the browser (Ctrl+F5) many times, but was same.
Today, it suddenly start to work as expected. I think it was browser problem. Ctrl-F5 didn't work for DiyBMS page. Page info was stored somewhere in browser's memory and got long time to disappear.

I changed battery type at inverter site to and it started charging. Now I have set Freedom Won Lite, which have higher top voltage and it 'talks' with Pylon emulation.
The inverter seems to have internal database for supported batteries.
If I set PylonTech 3000, inverter's hidden battery status page shows 'recommended-vcharge' value like 53,2V and stops charging at that voltage. Voltage is not enough for Leaf cell's top 54V and bottom 45V.
Because Leaf cells are twins, connection for 13cells is a bit difficult.
I'm not familiar with coding and tried to read code, if it is possible to cheat the inverter by sending lower voltage info via canbus.
Propably that will not help, because inverter 'knows' the maximum voltage and will set it internally.

There's many other selectable battery types available in inverter's setup and I found, that YUASA LIM40E-14T1-J1 is close of my Leaf cells, but it doesn't 'underestand' Pylon or Victron emulation. Tried to find the protocol info from web, but no success.
Any suggestions to sniff the data at canbus and does it help to make YUASA emulation ?

With in the tests, I found that DiyBms shows battery discharge around 2,5kW. Same time grid feed was zero.
My normal consumption is around half from that.
I disconnect inverter and confirmed consumption of around 1,3kW
Any ideas, why consumption show twice as real ?

**Comment by stuartpittaway** [comment]
Have you connected the DIYBMS to the inverter/charger using a CANBUS cable ?

Any decent inverter will listen to the BMS and use its settings for voltage/current, otherwise there isn't much point in having a BMS!

**Comment by deekoowee** [comment]
Yes, the CANBUS cable is connected and voltage & current & temperature data from DIYBMS can be seen at inverter's hidden web page.

With PylonTech (3000) settings, the inverter charged only around ½C from one PylonTech battery max 37A charge current. 
I was thinking, that when inverter receives incorrect  quantity of battery modules #189 from DIYBMS and will charge lower current.
