### ISSUE TITLE
Nominal Battery Capacity back to 280Ah after restart

### ISSUE THREAD

**Issue by maciejkrasuski** [stuartpittaway/diyBMSv4ESP32#197]
After restarting the controller this settings sets back to 280Ah.

**Hardware/Software Versions**
Controller version (from PCB): 4.2
(below can be obtained from the "About" page in the controller web interface)
Processor: ESP32
Version: [4e72db94af375c391bad47b9b98507b3271b069d]
Compiled: 2023-03-29T08:22:59.136Z

**To Reproduce**
1. Go to 'Charge/Discharge Settings'
2. Set Nominal Battery Capacity to 600Ah
3. Restart controller
4. The settings is 280Ah again

**Comment by stuartpittaway** [comment]
Is this on the charging page?

![image](https://user-images.githubusercontent.com/1201909/231406492-c02fc87b-ed7b-4d28-a90b-4999a4e569c3.png)


Did you click "save" after editing the value?  Did the web page show "success" message after clicking save?

**Comment by maciejkrasuski** [comment]
Yes - exactly. I don't know if this is important, but I have victron selected on that combobox above.

**Comment by stuartpittaway** [comment]
Hi @maciejkrasuski 

I've reviewed the code and cannot see any issues with that particular field, the same code/settings are used to store all the values on that page - is this problem only occurring with that one field?
