### ISSUE TITLE
Compulsory Username/password for mqtt

### ISSUE THREAD

**Issue by mbrunton22** [stuartpittaway/diyBMSv4ESP32#198]
I run a local mqtt server without a username and password. The UI seems to make the username compulsory. It would be great if this was optional in the UI.

![diybms](https://user-images.githubusercontent.com/65273946/230829304-6925e31c-1d2a-4832-bb5b-f7a6ce1dab96.jpg)

**Comment by stuartpittaway** [comment]
Changes are in the next release

**Comment by stuartpittaway** [comment]
@mbrunton22 release is out, can you test and report back?

**Comment by mbrunton22** [comment]
Yep, that worked perfectly!

Thanks very much!
