### ISSUE TITLE
Cells V4.4 9600Baud Resistor to 41.2 ohm

### ISSUE THREAD

**Issue by Michi202020** [stuartpittaway/diyBMSv4ESP32#212]
Hello Stuart,

i need for the ID3 Batterie the code for Resistor 41.2 Ohm.
Please can you make me this for me?
I start to install 30 peases from ID3 Batterie withe 6,85 kwh. Later I sent you Picture from my Project.

Many Tahnks and Best Regards
Michael .G

**Comment by stuartpittaway** [comment]
Hi @Michi202020 

Do you mean the balance resistor value?

This is a change you can do yourself.  If you edit the "platform.ini" file using VSCode, look for the values ```-DLOAD_RESISTANCE=3.30```  Simply change the 3.30 to 41.2 and compile the code.

**Comment by Michi202020** [comment]
Hy Stuart,

ok i will check this! Many thanks!

**Comment by Michi202020** [comment]
Hello, pleas close this is finished!
