### ISSUE TITLE
A question about the 2 new features in the all-in-one board compared to the ESP32 controller

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4ESP32#230]
Hello Stuart
You have added two new functions to the all-in-one board for using active balancers. Was that even necessary? In the rules you can already define relays for cell over voltage and bank range in order to be able to switch on an active balancer.
What is the difference to the 2 functions you showed in your video?

**Comment by stuartpittaway** [comment]
The benefit of the relays on the monitoring boards is that it allows you to have a balancer per cell-pack rather than limited to just one or two based off the controller relays.
