### ISSUE TITLE
daily Ah out/in view wrong

### ISSUE THREAD

**Issue by buddhafragt** [stuartpittaway/diyBMSv4ESP32#231]
Hello,
the daily Ah out/in view is wrong
![diybms](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/680639/e1149609-bc26-43da-8b98-d86fef6c805e)

**Comment by stuartpittaway** [comment]
Hello @buddhafragt 

Can you tell me some more about the system you are running - are you using the latest versions of code on both controller and the external current monitor/shunt (unless using the onboard one) ?

Does this happen all the time, or is this the first power on?

If you use the "reset daily amp hour" button, does the value correct to zero?

![image](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/1201909/252523e9-b13d-40d2-a7f6-abbf0a81a5ea)

Have you been using the set S.o.C function?

**Comment by stuartpittaway** [comment]
Ok, if the reset option doesn't work, you need to update the shunt firmware/code. You are running with a mix of incompatible versions

**Comment by buddhafragt** [comment]
Thank you Stuart, I will do it!

**Comment by stuartpittaway** [comment]
Did you get chance to test this?
