### ISSUE TITLE
SOC save and restore

### ISSUE THREAD

**Issue by buddhafragt** [stuartpittaway/diyBMSv4ESP32#241]
Hi Stuart,
Do you think it is possible to save the SOC continuously and to restore this value during a system restart? It's not so nice to always have 6% or so after a reboot.

**Comment by stuartpittaway** [comment]
Regularly saving the SoC to flash would likely cause the flash to get worn out over a period of time.

You can manually set the SoC using the utility menu in the web interface, so quite easy to reset to as it was.
