### ISSUE TITLE
Reset Daily Amp Hour Count

### ISSUE THREAD

**Issue by magpern** [stuartpittaway/diyBMSv4ESP32#246]
I have just upgraded to latest version from a really old version.
The Daily Amp Hour Count is a really wierd value.
![image](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/6589760/7c6ebe7b-be7e-476f-aae7-a8b4fd706022)

I have tried to reset it with the "Reset Daily Amp Hour Count"-button, but that buttom doesn't do anything.

Processor: ESP32
Version: [169a4ea838986b107de2cf4abc0ed219f89c2bbc](https://github.com/stuartpittaway/diyBMSv4ESP32/commit/169a4ea838986b107de2cf4abc0ed219f89c2bbc)
Compiled: 2023-09-12T10:47:12.660Z

**Comment by stuartpittaway** [comment]
Have you updated the current shunt firmware as well?  The two are likely out of sync.

**Comment by magpern** [comment]
Update of firmware on current sensor solved problem
