### ISSUE TITLE
improve Victron integration change CAN speed between 500 & 250 kbps

### ISSUE THREAD

**Issue by Bingo2023** [stuartpittaway/diyBMSv4ESP32#251]
current status: CAN is set to 500 kbps
improvement: CAN can be set to 500 kbps or 250 kbps

Background
500 kbps are used to connect diyBMS and VenusOS (speed 500 kbps). Inverter like Multi Plus II is connected via VE.bus (separate communication line e.g. with USB dongel).

250 kbps can be used to connect diyBMS and VenusOS AND new RS Multi Inverter via CAN (speed 250 kbps). In VenusOS you have to lower the CAN speed to 250 kbps (RS Multi and other Victron devices can only do 250 kbps), see attached screenshot. 

![2023-10-29_17h07_52](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/61052575/5ffc3016-e08d-419d-9842-3b5630a7401e)

**Comment by stuartpittaway** [comment]
Have you tried changing the code yourself to see if this works?

**Comment by Bingo2023** [comment]
at a quick search, I could not find the place where CAN in configured. Would you point it point out?

**Comment by stuartpittaway** [comment]
https://github.com/stuartpittaway/diyBMSv4ESP32/blob/0f7f03c1c13382ed7031464baa92671fe778afc3/ESPController/src/HAL_ESP32.cpp#L287

**Comment by Bingo2023** [comment]
I changed the code and compiled and flasht ---> it works perfect :)
If you could make this change switchable on the Victron/PylonTech setting page would be a real benefit.

![2023-11-01_20h21_23](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/61052575/d8f608ee-9d99-4fbc-9529-1d5a4aef2188)
![2023-11-01_20h19_34](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/61052575/121eee16-5f7c-4faa-8afe-138aaa6b799c)
![2023-11-01_20h19_45](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/61052575/ba376ffb-5ee7-4986-9046-394f864c2e70)
![2023-11-01_20h20_04](https://github.com/stuartpittaway/diyBMSv4ESP32/assets/61052575/9213fdec-478e-4747-a0cd-7c14ef9d08d1)
