### ISSUE TITLE
Victron support

### ISSUE THREAD

**Issue by donnib** [stuartpittaway/diyBMSv4ESP32#27]
Hi @stuartpittaway ,
We discussed Victron support on the Forum. There is a big customer base of Victron users out there and i think Victron support would make this project shine even more so i asked the the question on the Victron Forum how we could get started. You may want to participate especially if i am saying something wrong.

https://community.victronenergy.com/questions/93436/what-kind-of-protocol-do-you-recommend-to-implemen.html

/donnib aka Peter on Victron forum

**Comment by stuartpittaway** [comment]
Great, thanks for asking - looks like CANBUS is the way forward

**Comment by donnib** [comment]
Sure is, i am willing to help out with testing if we get to that point.

**Comment by stuartpittaway** [comment]
I've been offered a Cerbo GX unit from somebody on the forum to play with.

I wonder if Victron do R&D kit for development purposes?

**Comment by donnib** [comment]
@stuartpittaway yes and that's a great start, in practice we need to test it in real life and that i can do. I can start preparing to make the new controller, i only have the old one but if you start on doing the implementation for the CAN-BMS support for Victron i have an incentive ;) 
In regard to your question, no i haven't heard of that. 
The CerboGX is the brain in the whole system so i guess that should be enough to get started but i am unsure, we probably have to ask @mpvader aka Matthijs Vader from Victron.

**Comment by donnib** [comment]
@stuartpittaway i have sent you a PB in the openenergymonitor.org with my email so we can talk.

**Comment by donnib** [comment]
@stuartpittaway check my PM

**Comment by stuartpittaway** [comment]
I've received a Cerbo GX unit from Victron, and hope to explore that soon.

**Comment by donnib** [comment]
@stuartpittaway great Stuart, ask away if i can help in anyway

**Comment by donnib** [comment]
Hi @stuartpittaway,
Have you had anytime to look at this ?

**Comment by stuartpittaway** [comment]
Yes, I've got basic CANBUS Victron support working now.  The code is no where near stable enough for release yet!

![image](https://user-images.githubusercontent.com/1201909/128675484-16ab80c9-63a9-415d-ba11-da4977ed84c1.png)

![image](https://user-images.githubusercontent.com/1201909/128675493-68cec4cd-cc00-413d-9927-3126adf072d0.png)

**Comment by donnib** [comment]
@stuartpittaway pretty cool ! Well done. Great to hear you have reached so far ;)

**Comment by SergioRius** [comment]
@stuartpittaway Amazing! You're the boss. Cheer up.

**Comment by pas940** [comment]
This is super exciting. Just looking at your bms to add to my victron system. It looks hard to find hardware at the moment. Most out of stock etc. Will the can be on the same hardware or will it be a new controller, and do you maintain compatibility between all cell models? Just trying to work out what I need.

**Comment by stuartpittaway** [comment]
No hardware changes needed for the can to work, and still supports the same cells.

You will probably need the current monitor as well to make it fully functional.

**Comment by jdevine82** [comment]
What about adding a dynamic charge limit. What I mean is using the battery current shunt and the charge limit setting you have but make it so that it follows the battery current plus whatever balance current is needed. This will allow the inverter to still use whatever current it wants. This will work better in a full house off grid as it will allow balancing while the load is dynamic.

**Comment by stuartpittaway** [comment]
> This is super exciting. Just looking at your bms to add to my victron system. It looks hard to find hardware at the moment. Most out of stock etc. Will the can be on the same hardware or will it be a new controller, and do you maintain compatibility between all cell models? Just trying to work out what I need.

It is difficult to find the correct parts at the moment - low stock levels for a long time now.  All the modules are still supported, although if you are building new, use the 4.4 version.

**Comment by stuartpittaway** [comment]
> What about adding a dynamic charge limit.

I'd have to give that some thought on how it would work.

**Comment by stuartpittaway** [comment]
I'm going to close this issue, as its got several different comments/threads running.  Please open separate issues for different topics. Thanks.
