### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by sdqf-20** [stuartpittaway/diyBMSv4ESP32#3]
Hello from Russia! I ordered circuit boards to repeat the project. I can translate the web interface and instructions into Russian, but I don’t see where the language data is stored. Sorry for my English if there are any errors.

Best Regards 
Evgeny

**Comment by stuartpittaway** [comment]
Hi Martin, did you make any progress with this?  I may want to change the language settings into run-time Javascript rather than at compile time.  I can probably copy + paste any progress that you have made so far.

**Comment by stuartpittaway** [comment]
I've now generated lots of language files, but not Russian.

Happy to add, if you/anyone wants to take on the challenge

**Comment by sdqf-20** [comment]
Please show me where to find the files to edit. Ready to add Russian

**Comment by stuartpittaway** [comment]
Here is the file in a new branch.

https://github.com/stuartpittaway/diyBMSv4ESP32/blob/RussianLangSupport/ESPController/web_src/lang_ru.js

At the moment, all the words are in English, so just need to edit that file to add the translations.

**Comment by stuartpittaway** [comment]
Hello @sdqf-20 did you try and edit the Russian language files?
