### ISSUE TITLE
Influx Integration only working for bank 0

### ISSUE THREAD

**Issue by dakoal** [stuartpittaway/diyBMSv4ESP32#30]
Influx Integration only working for bank 0

All following banks show same values as first one.

**Comment by dakoal** [comment]
Is there an update?

**Comment by stuartpittaway** [comment]
I've fixed a related bug today which causes the controller to reboot due to low memory.

I'll take a look at this issue soon

**Comment by stuartpittaway** [comment]
Hi @dakoal.

Think I've fixed the issue, and at the same time I've upgraded the code to support the InfluxDB v2 API

The code is in this branch - are you okay compiling the code from this to test?

https://github.com/stuartpittaway/diyBMSv4ESP32/tree/influxdb2

**Comment by dakoal** [comment]
I will try. Give you an answer here

**Comment by dakoal** [comment]
![image](https://user-images.githubusercontent.com/11591571/129671918-1b7203e2-b168-4888-84f8-1dd891eacdbc.png)

Which file to flash? is it simply the "IMG" or do I have to do some magic with the ELF?

**Comment by stuartpittaway** [comment]
If you have used platformio to compile it, just press the upload button in there (connect ESP32 using usb cable)

**Comment by dakoal** [comment]
I am in crete and Karl in Austria. My Laptop here is the one with platform io and karl has the system with 5 banks.

**Comment by stuartpittaway** [comment]
Ah ok, the ".bin" file should be the one to use.

You should be able to use a tool called "esptool.py" to send that to the ESP32
