### ISSUE TITLE
[Question] Networked logging

### ISSUE THREAD

**Issue by slundell** [stuartpittaway/diyBMSv4ESP32#32]
I am trying to figure out a few values from the rs485 data stream, but cannot always use the serial as Im sometimes too far from the boat. Is there any way to output debug values over network?

I have tried https://github.com/MalteJ/embedded-esp32-component-udp_logging which resulted in a hang on boot, which I could not debug, as I did not have access to serial. It was probably just a bad init on my part.

I have also written some rudamentary functions to just concatenate text serve it as a webpage, but that corrupted the stack. My fault as well :)

**Comment by stuartpittaway** [comment]
I've not really looked into network logging as I generally just use a USB cable
