### ISSUE TITLE
[UI Detail] Ah missing

### ISSUE THREAD

**Issue by slundell** [stuartpittaway/diyBMSv4ESP32#33]
Amp hour in and out info boxes are missing unit (Ah). See image.
![image](https://user-images.githubusercontent.com/19412141/126861359-00a2c79a-0eae-4ece-b3fe-c27b465d0dd3.png)

**Comment by stuartpittaway** [comment]
Adding in the unit makes the text in the box wrap, I didn't think it important as the ah is already in the box title
