### ISSUE TITLE
currentMonitor.timestamp always zero

### ISSUE THREAD

**Issue by slundell** [stuartpittaway/diyBMSv4ESP32#34]
I tried to use the condition `currentMonitor.timestamp == 0` to check if the modbus parsing was in its first iteration. Unfortunately this always holds true as `esp_timer_get_time()` seems to always return 0.

**Comment by stuartpittaway** [comment]
It's expecting to get the timestamp from NTP server, do you have access to the internet?

**Comment by stuartpittaway** [comment]
Did you get anywhere with this?

**Comment by stuartpittaway** [comment]
Closing as no update
