### ISSUE TITLE
[Question] Settings survive after flash new version?

### ISSUE THREAD

**Issue by SergioRius** [stuartpittaway/diyBMSv4ESP32#39]
I've just upgraded to the latest automatic version and I've noticed that all the settings have been lost, including wifi connection, shunt config and rules. I'm not using the onboard sd slot nor the display one.

Should the settings had survived if a SD card was used? The screen SD port can also be used? (the onboard port requires disassembly of the screen and the whole bundle if it is inside a box.

**Comment by stuartpittaway** [comment]
This is related to #58
