### ISSUE TITLE
uptime displayed wrong/rebooting when data cannot be written

### ISSUE THREAD

**Issue by voort4444** [stuartpittaway/diyBMSv4ESP32#48]
Hi Stuart, 
I downloaded and am currently testing the latest firmware (september 2021).
All spontaneaus rboots are gone!, thanks.
two issues I did find; the uptime counter is not correct;
When the 24hour mark had beenreached, the "day"count is the same as the "hour count", eg when it shoudl display 2days13 hours 5minutes, it shows: 13days13hours5minutes.

The other issues I found is;
when enabling logging via influxdb, but the influxdb server is not available (controllersnot able to write to influxdb server), then the controller reboots. (I tested when putting in wrong credentials, and also temporarily shutting down the influxdb server)

But despite these thing, I am very happy with the new firmware!

**Comment by stuartpittaway** [comment]
I'll use this issue to fix the up time counter showing incorrectly.

The influx issue is also captured in #51

**Comment by voort4444** [comment]
Thanks!
