### ISSUE TITLE
CANbus checkbox unselected on reboot

### ISSUE THREAD

**Issue by magpern** [stuartpittaway/diyBMSv4ESP32#55]
When rebooting diyBMS controller, the CANbus checkbox becomes unselected. CANbus communication is stopped
![image](https://user-images.githubusercontent.com/6589760/135982006-78baff71-4a00-4b15-91c7-40d94b6f4f77.png)

**Comment by stuartpittaway** [comment]
It also doesn't store the CVL/CCL/DCL settings between reboots either.
