### ISSUE TITLE
Firmware updates erase all settings, except wifi

### ISSUE THREAD

**Issue by magpern** [stuartpittaway/diyBMSv4ESP32#58]
When I did a firmware update, all settings, battery levels, relay settings, shunt settings where erased. Also influx and mqtt settings where erased.
I selected "Wipe Eeprom = No"

The wifi setting was not erased. I did press save wifi and save configuration before the firmware update

![image](https://user-images.githubusercontent.com/6589760/135994908-d006f945-83ff-478f-919f-65d83f57e2c9.png)

**Comment by stuartpittaway** [comment]
Unfortunately this is how the current firmware updates work.  The WIFI details are stored on the SD card and automaticallly restored when powered up after an upgrade.

I intend to do the same with the rest of the system settings  - which is what the save configuration button intends to do, but not fully implemented.

**Comment by stuartpittaway** [comment]
The next version of the controller code supports saving and restoring configuration to the sd card.  (NOV2021 branch)
