### ISSUE TITLE
implement CAN Interface

### ISSUE THREAD

**Issue by fhorst1** [stuartpittaway/diyBMSv4ESP32#61]
Please add CAN support for the CAN port.

the request was also made here: https://community.openenergymonitor.org/t/diybms-v4/11292/3697
(with PDF to download)
The same information I have about the CAN usage for my inverters is inserted as jpg, as PDF can't be shared here :-)

-  CAN 2.0B
-  CAN Baud Rate：250kbps
-  11-bit identifiers
-  Little endian

<a href="https://ibb.co/0s1tnPv"><img src="https://i.ibb.co/z6CJmKD/canID.jpg" alt="canID" border="0"></a>

<a href="https://ibb.co/fDTY6Sd"><img src="https://i.ibb.co/xFrS9sq/CAN-2.jpg" alt="CAN-2" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>best image hosting</a><br />

<a href="https://ibb.co/KD6Vtsk"><img src="https://i.ibb.co/r3k5BpS/CAN3.jpg" alt="CAN3" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>best image hosting</a><br />

<a href="https://ibb.co/XWBB8XY"><img src="https://i.ibb.co/51DDFTK/CAN4.jpg" alt="CAN4" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>best image hosting</a><br />

**Comment by stuartpittaway** [comment]
@fhorst1 what brand are these inverters?  Do you have a link to the supplier/shop?

The BMS should be able to easily transmit those CAN messages, its very similar to the Victron protocols.

**Comment by fhorst1** [comment]
Brand name is "Sorotec"
Type Revo II

http://www.sorotecups.com/product-detail/on-grid-off-grid-hybrid-inverter/

It's a nice one, price quality wise.
Not Victron, also not Victron price.

Energy conversion is good and "clean" Mppt max is 4500 watt, their information of 5500 is incorrect.
Even with 8000 watt of possible solar.... Stuck at 4500w :-)

Different story.
I need to build my own mppt that's capable of higer voltage (350-400v) and higher capacity (7500-12500W) on 51.2 LiFePO4.
Perhaps you know about a development?

Anyway...
The information earlier provided for the CAN, I don't know if it's a standard with all information in the same location, of its anarchy....

December time to update the project, I'll see if it can talk now CAN is activated in de firmware.

Thank you.

**Comment by stuartpittaway** [comment]
No update on this issue since 2021, so going to close, please re-open if needed.
