### ISSUE TITLE
New feature: SOC on LCD

### ISSUE THREAD

**Issue by jdevine82** [stuartpittaway/diyBMSv4ESP32#66]
Just wondering if it is easy to add SOC as a % to display of controller from current monitor. I know you are not aiming for much info on the display but this is a pretty basic one.
Jason

**Comment by stuartpittaway** [comment]
Hi, @jdevine82 the SOC should now be visible on the TFT display - please update to the latest release and let me know how it works for you.

**Comment by jdevine82** [comment]
Thanks Stuart
uploaded today and appears to work perfectly. Will let you know if anything develops. I see its in main release already.
Cheers
Jason
