### ISSUE TITLE
 Browser language does not make relays work

### ISSUE THREAD

**Issue by manuromero05** [stuartpittaway/diyBMSv4ESP32#7]
If you have changed the default language in your browser other than English, in this case Spanish, the relays do not act.

We also find that if the screen resolution is small (ex: 1080x720) the relays do not always act.

Gracias.
Slds.

**Comment by stuartpittaway** [comment]
Is this still an issue with the latest version?

**Comment by manuromero05** [comment]
The problem still persists, but now it doesn't matter when you have the Spanish language in the settings. 
That's how it works very well. 

Thanks a lot.

**Comment by Garkus98** [comment]
there is also a problem with the Russian language on the latest firmware

**Comment by stuartpittaway** [comment]
Is this still a problem?

**Comment by manuromero05** [comment]
Hi works correctly

Regards
