### ISSUE TITLE
Packet Loss

### ISSUE THREAD

**Issue by allanlind** [stuartpittaway/diyBMSv4ESP32#74]
I seem to be getting packet loss, and the data LEDs seem to illuminate up as far as module 16 when the data is going around the daisy chain but there is a few second delay before module 17 data LED illuminates, then the next 16 modules flash the data LED in sequence.
Version is Compiled_Firmware_2021-12-06-15-12.
![image](https://user-images.githubusercontent.com/6001983/147375500-ba082091-a81f-4737-a2d3-6dd176d8c101.png)

![image](https://user-images.githubusercontent.com/6001983/147375512-6554f8aa-7705-46d7-b304-655d046adf4b.png)

**Comment by stuartpittaway** [comment]
Another user has reported similar behaviour which I've fixed and they are just finishing testing.

What version of the modules are you using?

**Comment by allanlind** [comment]
Modules are 4.4 and flashed from the controller with Dec 6 2021 compiled version.

**Comment by allanlind** [comment]
Another problem I discovered is that if I connect any more than about 84 modules at a time I lose connectivity with the last modules int the group after an hour or so. I currently have a string of 112 modules. 
Stuart, is there any logs I can send you?
I sent Tim Yorba 10 of the integrated 14 cell boards so he will be able to run tests as well as soon as he receives the shipment.

**Comment by allanlind** [comment]
![image](https://user-images.githubusercontent.com/6001983/147859587-f1960789-3ae5-432a-a73e-d8fafe5de6ff.jpg)

**Comment by stuartpittaway** [comment]
The high number of cells is currently being worked on and looks like we have a suitable fix for it, assuming they are 4.4 version

**Comment by allanlind** [comment]
Fantastic thank you. I’ll keep an eye out for it.

**Comment by stuartpittaway** [comment]
@allanlind I've just merged the code into the master branch, so a new release should be available - its just a controller update.

**Comment by allanlind** [comment]
Thanks Stuart. That works better. Not losing connectivity to the last 20 or so modules now. 
Still having those big delays though. 
I was discussing with Tim Yorba and he suggested we might want to increase the watchdog timeout as the modules may be timing out waiting for the next round of packets.

**Comment by stuartpittaway** [comment]
You can't change the watchdog, it's hardware based and currently at its maximum of 8 seconds.

What do you mean by delays? Are You using v4.4 modules at a higher Comms speed?

**Comment by allanlind** [comment]
Stuart, as I said previously, the blue data LEDs illuminate up as far as module 16 when the data is going around the daisy chain but there is a few seconds delay before module 17 data LED illuminates, then the next 16 modules flash the data LEDs in sequence around the loop, always in blocks of 16 modules. 
I have flashed all the modules at 9.6k.

**Comment by stuartpittaway** [comment]
That's perfectly normal behaviour and how the system works. Only 16 modules can be addressed at a time, so the 17 module has to wait for the request to skip through the previous 16 modules before the lights flash.

**Comment by allanlind** [comment]
Whew! thanks Stuart.  Now I can sleep well.

**Comment by stuartpittaway** [comment]
More importantly, since the update, all modules are reporting correctly and you don't see any "OOS" errors ?

What round trip time do you have?

**Comment by allanlind** [comment]
![29FA2CD0-1281-48DE-B9DB-FFA4AE77E9EF](https://user-images.githubusercontent.com/6001983/148367558-9094b0ad-5f2d-40a7-abc4-cad554d60dea.png)
![5210D15B-917E-4783-88AC-18726F969117](https://user-images.githubusercontent.com/6001983/148367571-2f90239d-4b16-49e0-85f8-0acf282588b6.png)

**Comment by allanlind** [comment]
just under 6 seconds. Only a few OOS errors and looks like most packets are arriving back.
