### ISSUE TITLE
switching from English to Russian

### ISSUE THREAD

**Issue by Garkus98** [stuartpittaway/diyBMSv4ESP32#77]
When switching from English to Russian in the panel on the newest firmware, it remains English, although everything has been translated. By the way, German is also not translated.
![Capture](https://user-images.githubusercontent.com/76440047/147844911-c1bd30ed-70b6-414b-97de-d5343195fcee.JPG)

**Comment by Jestergnet** [comment]
I also set the language to Russian, but remained in English.

**Comment by Jestergnet** [comment]
Причину нашел, нужно в файле ESPController/web_src/lang_ru.js найти:
$("#rt2").text("Правила обрабатываются от самого низкого приоритета до самого высокого(снизу вверх).Управляйте реле с помощью опций. Значение "X" означает, что вам все равно/оставьте значение, определенное правилами с более низким приоритетом.");
$("#rt3").text("Правила срабатывают, когда соответствующее значение соответствует или превышает значение "триггера". Правило будет отключено только тогда, когда значение затем передаст значение "сброс". Это может помочь предотвратить грохот реле и быстрое включение / выключение правил.");
$("#rt4").text("Правила "Таймер 1" и "Таймер 2" допускают работу по времени, это правило активно, когда достигнуто количество минут после полуночи, например, установка триггера "Таймер 1" на 495 и сброс до 555 включится в 8: 15 утра и выключится в 9: 15 утра. Это работает только при подключении к Интернету для регулярных обновлений времени.");

Заменить на:
$("#rt2").text("Правила обрабатываются от самого низкого приоритета до самого высокого(снизу вверх).Управляйте реле с помощью опций. Значение \"X\" означает, что вам все равно/оставьте значение, определенное правилами с более низким приоритетом.");
$("#rt3").text("Правила срабатывают, когда соответствующее значение соответствует или превышает значение \"триггера\". Правило будет отключено только тогда, когда значение затем передаст значение \"сброс\". Это может помочь предотвратить грохот реле и быстрое включение / выключение правил.");
$("#rt4").text("Правила \"Таймер 1\" и \"Таймер 2\" допускают работу по времени, это правило активно, когда достигнуто количество минут после полуночи, например, установка триггера \"Таймер 1\" на 495 и сброс до 555 включится в 8: 15 утра и выключится в 9: 15 утра. Это работает только при подключении к Интернету для регулярных обновлений времени.");

**Comment by Garkus98** [comment]
так а ошибка то где? в каком именно слове/месте?

**Comment by Garkus98** [comment]
исправление сейчас внесу спасибо

**Comment by Jestergnet** [comment]
Не экранировали кавычки, НЕ правильный например:
$("#rt2").text("текст текст "X" текст");

Правильно:
$("#rt2").text("текст текст \"X\" текст");
или
$("#rt2").text("текст текст 'X' текст");

**Comment by Garkus98** [comment]
ясно спасибо сейчас исправлю
