### ISSUE TITLE
Compile errors when compiling on certain dates

### ISSUE THREAD

**Issue by delboy711** [stuartpittaway/diyBMSv4ESP32#89]
I noticed today diYBMS would not compile with the error
`invalid digit "8" in octal constant`

On investigation the cause was in buildscript_versioning.py on Line 91
`f.write(datetime.datetime.utcnow().strftime("%W"))`
The format code %W produces a two character string to represent the week number. We are currently in week 8 so the string is "08" which thanks to the leading '0' is then interpreted by the c++ compiler as an octal integer literal.

Changing line 91 to
`f.write(datetime.datetime.utcnow().strftime("%W").lstrip("0"))`
works OK for me.

**Comment by stuartpittaway** [comment]
Great spot/fix.  Thanks.
